// packages/kitcn/src/solid/convex-auth-provider.tsx
/** @jsxImportSource solid-js */

/**
 * Unified Convex + Better Auth provider for SolidJS
 *
 * Port of the React ConvexAuthProvider to SolidJS.
 * Handles token sync and auth callbacks.
 */

import type { ConvexClient } from 'convex/browser';
import { createEffect, type JSX, onMount, type ParentProps } from 'solid-js';

import { CRPCClientError, defaultIsUnauthorized } from '../crpc/error';
import { decodeJwtIdentity } from '../internal/jwt';
import {
  AuthProvider,
  decodeJwtExp,
  FetchAccessTokenContext,
  useAuthStore,
} from './auth-store';
import { ConvexProviderWithAuth, useConvexAuth } from './convex-solid';
import type { SolidAuthProviderClient } from './types';

type AuthGetSession = (options?: {
  fetchOptions?: {
    credentials?: RequestCredentials;
    headers?: Record<string, string>;
  };
}) => Promise<unknown> | unknown;

export type ConvexAuthProviderProps = {
  children: JSX.Element;
  /** Convex client instance */
  client: ConvexClient;
  /** Better Auth client instance */
  authClient: SolidAuthProviderClient;
  /** Initial session token (from SSR) */
  initialToken?: string;
  /** Callback when mutation called while unauthorized */
  onMutationUnauthorized?: () => void;
  /** Callback when query called while unauthorized */
  onQueryUnauthorized?: (info: { queryName: string }) => void;
  /** Custom function to detect UNAUTHORIZED errors. Default checks code property. */
  isUnauthorized?: (error: unknown) => boolean;
};

const defaultMutationHandler = () => {
  throw new CRPCClientError({
    code: 'UNAUTHORIZED',
    functionName: 'mutation',
  });
};

const hasActiveSessionData = (session: unknown) => {
  if (!session || typeof session !== 'object') {
    return false;
  }
  return Boolean((session as { session?: unknown }).session);
};

const getSessionId = (sessionData: unknown): string | undefined => {
  if (!sessionData || typeof sessionData !== 'object') {
    return;
  }
  const session = (sessionData as { session?: unknown }).session;
  if (!session || typeof session !== 'object') {
    return;
  }
  const id = (session as { id?: unknown }).id;
  return typeof id === 'string' ? id : undefined;
};

/**
 * Unified auth provider for Convex + Better Auth (SolidJS).
 * Handles token sync and auth callbacks.
 *
 * Structure: AuthProvider wraps ConvexAuthProviderInner so that
 * useAuthStore() is available when creating fetchAccessToken.
 */
export function ConvexAuthProvider(props: ConvexAuthProviderProps) {
  useOTTHandler(props.authClient);

  const tokenValues = () => ({
    expiresAt: props.initialToken ? decodeJwtExp(props.initialToken) : null,
    token: props.initialToken ?? null,
  });

  return (
    <AuthProvider
      initialValues={tokenValues()}
      isUnauthorized={props.isUnauthorized ?? defaultIsUnauthorized}
      onMutationUnauthorized={
        props.onMutationUnauthorized ?? defaultMutationHandler
      }
      onQueryUnauthorized={props.onQueryUnauthorized ?? (() => {})}
    >
      <ConvexAuthProviderInner
        authClient={props.authClient}
        client={props.client}
      >
        {props.children}
      </ConvexAuthProviderInner>
    </AuthProvider>
  );
}

/**
 * Inner provider that has access to AuthStore via useAuthStore().
 * Creates fetchAccessToken and passes it through context.
 */
function ConvexAuthProviderInner(
  props: ParentProps<{
    client: ConvexClient;
    authClient: SolidAuthProviderClient;
  }>
) {
  const authStore = useAuthStore();

  // In Solid, useSession returns an Accessor
  const sessionAccessor = props.authClient.useSession();

  // Stable ref for pending token promise (no re-renders in Solid)
  let pendingTokenPromise: Promise<string | null> | null = null;

  // Clear token when session becomes null (logout)
  createEffect(() => {
    const sessionState = sessionAccessor();
    const session = sessionState.data;
    const isPending = sessionState.isPending;

    if (!hasActiveSessionData(session) && !isPending) {
      authStore.set('token', null);
      authStore.set('expiresAt', null);
      authStore.set('isAuthenticated', false);
    }
  });

  // Stable fetchAccessToken - no useCallback needed in Solid
  const fetchAccessToken = async ({
    forceRefreshToken = false,
  }: {
    forceRefreshToken?: boolean;
  } = {}) => {
    const sessionState = sessionAccessor();
    const currentSession = sessionState.data;
    const currentIsPending = sessionState.isPending;
    const hasSession = hasActiveSessionData(currentSession);

    // If no session:
    // - If still pending (hydration), return cached token from SSR
    // - If not pending (confirmed no session), clear cache
    if (!hasSession) {
      if (!currentIsPending) {
        authStore.set('token', null);
        authStore.set('expiresAt', null);
      }
      return authStore.get('token');
    }

    // Check cached JWT from store
    const cachedToken = authStore.get('token');
    const expiresAt = authStore.get('expiresAt');
    const timeRemaining = expiresAt ? expiresAt - Date.now() : 0;

    // Return cached if valid and not forced (60s leeway)
    if (
      !forceRefreshToken &&
      cachedToken &&
      expiresAt &&
      timeRemaining >= 60_000
    ) {
      return cachedToken;
    }

    if (!forceRefreshToken && pendingTokenPromise) {
      return pendingTokenPromise;
    }

    const fetchOptions: {
      headers?: {
        Authorization: string;
      };
      throw: false;
    } = {
      throw: false,
    };
    if (cachedToken && decodeJwtExp(cachedToken) === null) {
      fetchOptions.headers = {
        Authorization: `Bearer ${cachedToken}`,
      };
    }

    // Fetch fresh JWT
    // biome-ignore lint/suspicious/noExplicitAny: convex plugin type
    pendingTokenPromise = (props.authClient as any).convex
      .token({ fetchOptions })
      .then((result: { data?: { token?: string | null } | null }) => {
        const jwt = result.data?.token || null;

        if (jwt) {
          const exp = decodeJwtExp(jwt);
          authStore.set('token', jwt);
          authStore.set('expiresAt', exp);
          return jwt;
        }

        authStore.set('token', null);
        authStore.set('expiresAt', null);
        return null;
      })
      .catch((error: unknown) => {
        authStore.set('token', null);
        authStore.set('expiresAt', null);
        console.error('[fetchAccessToken] error', error);
        return null;
      })
      .finally(() => {
        pendingTokenPromise = null;
      });

    return pendingTokenPromise;
  };

  // Create useAuth function for ConvexProviderWithAuth
  // In Solid, this is a plain function (stable, no useCallback needed)
  const useAuth = () => {
    const sessionState = sessionAccessor();
    const hasSession = hasActiveSessionData(sessionState.data);
    const sessionMissing = !hasSession && !sessionState.isPending;
    const token = authStore.get('token');

    return {
      identity:
        getSessionId(sessionState.data) ??
        (token ? decodeJwtIdentity(token) : null),
      isLoading: sessionState.isPending && !token,
      // If Better Auth confirms no session, stale JWT should not keep auth=true.
      isAuthenticated: sessionMissing ? false : hasSession || token !== null,
      fetchAccessToken,
    };
  };

  return (
    <FetchAccessTokenContext.Provider value={fetchAccessToken}>
      <ConvexProviderWithAuth client={props.client} useAuth={useAuth}>
        <AuthStateSync>{props.children}</AuthStateSync>
      </ConvexProviderWithAuth>
    </FetchAccessTokenContext.Provider>
  );
}

/**
 * Syncs auth state from useConvexAuth() to the auth store.
 * MUST be inside ConvexProviderWithAuth to access useConvexAuth().
 *
 * Defensive isLoading computation handles SSR hydration race:
 * 1. SSR sets token from cookie
 * 2. Client hydrates
 * 3. Better Auth's useSession() briefly returns null before loading cookie
 * 4. Convex sets isConvexAuthenticated = false (no auth to wait for)
 * 5. Without defensive check, we'd sync { isLoading: false, isAuthenticated: false }
 * 6. Queries would throw UNAUTHORIZED before token is validated
 */
function AuthStateSync(props: ParentProps) {
  // Don't destructure — access via getters inside createEffect to preserve reactivity
  const convexAuth = useConvexAuth();
  const authStore = useAuthStore();

  createEffect(() => {
    // Read token inside effect so changes are tracked
    const token = authStore.get('token');

    // DEFENSIVE: If we have a token but Convex says not authenticated,
    // stay in loading state to avoid UNAUTHORIZED errors during hydration
    const hasTokenButNotAuth = !!token && !convexAuth.isAuthenticated;
    const isLoading = convexAuth.isLoading || hasTokenButNotAuth;

    authStore.set('isLoading', isLoading);
    authStore.set('isAuthenticated', convexAuth.isAuthenticated);
  });

  return props.children;
}

/**
 * Handles cross-domain one-time token (OTT) verification.
 */
function useOTTHandler(authClient: SolidAuthProviderClient) {
  onMount(async () => {
    if (typeof window === 'undefined' || !window.location?.href) {
      return;
    }

    const url = new URL(window.location.href);
    const token = url.searchParams.get('ott');

    if (token) {
      // biome-ignore lint/suspicious/noExplicitAny: cross-domain plugin type
      const authClientWithCrossDomain = authClient as any;
      url.searchParams.delete('ott');
      window.history.replaceState({}, '', url);
      const result =
        await authClientWithCrossDomain.crossDomain.oneTimeToken.verify({
          token,
        });
      const session = result.data?.session;

      if (session) {
        const getSession = authClient.getSession as AuthGetSession | undefined;
        await getSession?.({
          fetchOptions: {
            headers: {
              Authorization: `Bearer ${session.token}`,
            },
          },
        });
        authClientWithCrossDomain.updateSession();
      }
    }
  });
}

// packages/kitcn/src/auth-client/convex-auth-provider.tsx
'use client';

/**
 * Unified Convex + Better Auth provider
 */

import type { AuthTokenFetcher } from 'convex/browser';
import type { ConvexReactClient } from 'convex/react';
import { useConvexAuth } from 'convex/react';
import type { ReactNode } from 'react';
import { useCallback, useEffect, useMemo, useRef } from 'react';

import { CRPCClientError, defaultIsUnauthorized } from '../crpc/error';
import {
  clearAuthSessionFallback,
  readAuthSessionFallbackData,
  readAuthSessionFallbackToken,
  writeAuthSessionFallbackData,
} from '../react/auth-session-fallback';
import {
  AUTH_SESSION_SYNC_GRACE_MS,
  AuthProvider,
  type AuthStore,
  ConvexProviderWithAuth,
  decodeJwtExp,
  FetchAccessTokenContext,
  isSessionSyncGraceActive,
  useAuthStore,
  useAuthValue,
} from '../react/auth-store';
import type { ConvexAuthProviderClient } from './types';

type AuthClientFetch = ConvexAuthProviderClient & {
  $fetch?: (
    path: string,
    options?: {
      credentials?: RequestCredentials;
      headers?: Record<string, string>;
    }
  ) => Promise<{ data?: unknown } | null | undefined>;
};

type AuthGetSession = (options?: {
  fetchOptions?: {
    credentials?: RequestCredentials;
    headers?: Record<string, string>;
  };
}) => Promise<unknown> | unknown;

type AuthSessionAtom = {
  get?: () =>
    | {
        refetch?: (...args: never[]) => unknown;
      }
    | undefined;
  set?: (state: {
    data: unknown;
    error: null;
    isPending: false;
    isRefetching: false;
    refetch: (...args: never[]) => unknown;
  }) => void;
};

type IConvexReactClient = {
  setAuth(fetchToken: AuthTokenFetcher): void;
  clearAuth(): void;
};

export type ConvexAuthProviderQueryClient = {
  updateAuthStore: (authStore?: AuthStore) => void;
};

export type ConvexAuthProviderProps = {
  children: ReactNode;
  /** Convex client instance */
  client: ConvexReactClient;
  /** Better Auth client instance */
  authClient: ConvexAuthProviderClient;
  /** Shared Convex query client to sync with auth state */
  convexQueryClient?: ConvexAuthProviderQueryClient;
  /** Initial session token (from SSR) */
  initialToken?: string;
  /** Callback when mutation called while unauthorized */
  onMutationUnauthorized?: () => void;
  /** Callback when query called while unauthorized */
  onQueryUnauthorized?: (info: { queryName: string }) => void;
  /** Custom function to detect UNAUTHORIZED errors. Default checks code property. */
  isUnauthorized?: (error: unknown) => boolean;
};

const defaultMutationHandler = () => {
  throw new CRPCClientError({
    code: 'UNAUTHORIZED',
    functionName: 'mutation',
  });
};

const hasActiveSessionData = (session: unknown) => {
  if (!session || typeof session !== 'object') {
    return false;
  }
  return Boolean((session as { session?: unknown }).session);
};

const wait = (ms: number) =>
  new Promise((resolve) => {
    setTimeout(resolve, ms);
  });

const PERSISTED_TOKEN_ATTEMPTS = 3;
const PERSISTED_TOKEN_RETRY_BASE_MS = 100;

/**
 * `session` — the server returned one.
 * `none` — the server answered and there is no session. Definitive.
 * `unknown` — every attempt failed in transport. Says nothing about the token.
 */
type PersistedTokenOutcome =
  | { data: unknown; status: 'session' }
  | { status: 'none' }
  | { status: 'unknown' };

// `/get-session` answers an unknown or expired token with 200 and a null body,
// and the client resolves transport failures to `{ data: null, error }` instead
// of throwing. `.error` is the only thing separating "no session" from "the
// request never landed", so it has to be read.
const readAuthResult = (result: unknown) => {
  if (!result || typeof result !== 'object') {
    return { data: undefined, errored: true };
  }

  const { data, error } = result as { data?: unknown; error?: unknown };

  return { data, errored: Boolean(error) };
};

const getSessionFromPersistedToken = async (
  authClient: AuthClientFetch,
  token: string
): Promise<PersistedTokenOutcome> => {
  const getSession = authClient.getSession as AuthGetSession | undefined;

  for (let attempt = 0; attempt < PERSISTED_TOKEN_ATTEMPTS; attempt += 1) {
    // Only retries wait, so a live token costs one immediate request. The
    // backoff still covers the read-after-write window on a fresh sign-in.
    if (attempt > 0) {
      await wait(PERSISTED_TOKEN_RETRY_BASE_MS * 3 ** (attempt - 1));
    }

    let result: unknown;
    try {
      result = authClient.$fetch
        ? await authClient.$fetch('/get-session', {
            credentials: 'omit',
            headers: {
              Authorization: `Bearer ${token}`,
            },
          })
        : await getSession?.({
            fetchOptions: {
              credentials: 'omit',
              headers: {
                Authorization: `Bearer ${token}`,
              },
            },
          });
    } catch {
      continue;
    }

    const { data, errored } = readAuthResult(result);

    if (data) {
      return { data, status: 'session' };
    }
    if (!errored) {
      return { status: 'none' };
    }
  }

  return { status: 'unknown' };
};

const syncSessionAtom = (
  authClient: ConvexAuthProviderClient,
  sessionData: unknown
) => {
  const sessionAtom = authClient.$store?.atoms?.session as
    | AuthSessionAtom
    | undefined;
  if (
    typeof sessionAtom?.get !== 'function' ||
    typeof sessionAtom.set !== 'function'
  ) {
    return;
  }

  const current = sessionAtom.get();
  sessionAtom.set({
    data: sessionData,
    error: null,
    isPending: false,
    isRefetching: false,
    refetch: current?.refetch ?? (async () => {}),
  });
};

const clearSessionAtom = (authClient: ConvexAuthProviderClient) => {
  const sessionAtom = authClient.$store?.atoms?.session as
    | AuthSessionAtom
    | undefined;
  if (
    typeof sessionAtom?.get !== 'function' ||
    typeof sessionAtom.set !== 'function'
  ) {
    return;
  }

  const current = sessionAtom.get();
  sessionAtom.set({
    data: null,
    error: null,
    isPending: false,
    isRefetching: false,
    refetch: current?.refetch ?? (async () => {}),
  });
};

/**
 * Unified auth provider for Convex + Better Auth.
 * Handles token sync, HMR persistence, and auth callbacks.
 *
 * Structure: AuthProvider wraps ConvexAuthProviderInner so that
 * useAuthStore() is available when creating fetchAccessToken.
 */
export function ConvexAuthProvider({
  children,
  client,
  authClient,
  convexQueryClient,
  initialToken,
  onMutationUnauthorized,
  onQueryUnauthorized,
  isUnauthorized,
}: ConvexAuthProviderProps) {
  // Handle cross-domain one-time token
  useOTTHandler(authClient);

  // Memoize decoded JWT to avoid re-parsing on every render
  const tokenValues = useMemo(
    () => ({
      expiresAt: initialToken ? decodeJwtExp(initialToken) : null,
      token: initialToken ?? null,
    }),
    [initialToken]
  );

  // AuthProvider wraps inner so useAuthStore() is available inside
  // SSR initial values: set token/expiresAt, keep isLoading=true until Convex validates
  return (
    <AuthProvider
      initialValues={tokenValues}
      isUnauthorized={isUnauthorized ?? defaultIsUnauthorized}
      onMutationUnauthorized={onMutationUnauthorized ?? defaultMutationHandler}
      onQueryUnauthorized={onQueryUnauthorized ?? (() => {})}
    >
      <ConvexAuthProviderInner
        authClient={authClient}
        client={client}
        convexQueryClient={convexQueryClient}
      >
        {children}
      </ConvexAuthProviderInner>
    </AuthProvider>
  );
}

/**
 * Inner provider that has access to AuthStore via useAuthStore().
 * Creates fetchAccessToken and passes it through context (no race condition).
 */
function ConvexAuthProviderInner({
  children,
  client,
  authClient,
  convexQueryClient,
}: {
  children: ReactNode;
  client: ConvexReactClient;
  authClient: ConvexAuthProviderClient;
  convexQueryClient?: ConvexAuthProviderQueryClient;
}) {
  const authStore = useAuthStore();
  convexQueryClient?.updateAuthStore(authStore);

  const { data: session, isPending } = authClient.useSession();

  // Use refs to avoid recreating fetchAccessToken on session refetch (tab focus)
  // This prevents Convex SDK from calling setAuth() again and causing race conditions
  const sessionRef = useRef(session);
  const isPendingRef = useRef(isPending);
  const pendingTokenRef = useRef<Promise<string | null> | null>(null);
  sessionRef.current = session;
  isPendingRef.current = isPending;

  const getCachedJwt = useCallback(
    (minTimeRemainingMs = 0) => {
      const cachedToken = authStore.get('token');
      if (!cachedToken) {
        return null;
      }

      const expiresAt = decodeJwtExp(cachedToken);
      if (expiresAt === null || expiresAt <= Date.now() + minTimeRemainingMs) {
        return null;
      }

      return cachedToken;
    },
    [authStore]
  );

  // Clear token when session becomes null (logout)
  // This can't be inside fetchAccessToken because it's not called after logout
  useEffect(() => {
    if (hasActiveSessionData(session)) {
      authStore.set('sessionSyncGraceUntil', null);
      return;
    }

    if (
      !isPending &&
      !isSessionSyncGraceActive(authStore.get('sessionSyncGraceUntil'))
    ) {
      authStore.set('token', null);
      authStore.set('expiresAt', null);
      authStore.set('isAuthenticated', false);
      authStore.set('sessionSyncGraceUntil', null);
    }
  }, [session, isPending, authStore]);

  useEffect(() => {
    if (hasActiveSessionData(session) || isPending || authStore.get('token')) {
      return;
    }

    const persistedToken = readAuthSessionFallbackToken();
    const persistedSessionData = readAuthSessionFallbackData();
    if (
      !persistedToken ||
      (typeof authClient.getSession !== 'function' &&
        typeof (authClient as AuthClientFetch).$fetch !== 'function')
    ) {
      return;
    }

    let cancelled = false;

    authStore.set('token', persistedToken);
    authStore.set('expiresAt', decodeJwtExp(persistedToken));
    authStore.set(
      'sessionSyncGraceUntil',
      Date.now() + AUTH_SESSION_SYNC_GRACE_MS
    );
    if (persistedSessionData) {
      syncSessionAtom(authClient, persistedSessionData);
    }

    void getSessionFromPersistedToken(
      authClient as AuthClientFetch,
      persistedToken
    ).then((outcome) => {
      if (cancelled) {
        return;
      }

      if (outcome.status === 'session') {
        syncSessionAtom(authClient, outcome.data);
        writeAuthSessionFallbackData(outcome.data);
        return;
      }

      // Transport never answered. Signing out here would log a user out over a
      // dropped request, so the fallback token and grace window survive for the
      // next mount to retry.
      if (outcome.status === 'unknown') {
        return;
      }

      clearAuthSessionFallback();
      clearSessionAtom(authClient);
      authStore.set('token', null);
      authStore.set('expiresAt', null);
      authStore.set('sessionSyncGraceUntil', null);
    })
      // An unexpected failure is not evidence that the session is gone either.
      .catch(() => {});

    return () => {
      cancelled = true;
    };
  }, [session, isPending, authStore, authClient]);

  // Stable fetchAccessToken - only recreated when authStore/authClient change (rare)
  // Reads session/isPending from refs to avoid dependency on changing objects
  const fetchAccessToken = useCallback(
    async ({
      forceRefreshToken = false,
    }: {
      forceRefreshToken?: boolean;
    } = {}) => {
      const fetchFreshToken = () => {
        if (pendingTokenRef.current) {
          return pendingTokenRef.current;
        }

        const cachedToken = authStore.get('token');
        const fetchOptions: {
          credentials?: 'omit';
          headers?: {
            Authorization: string;
          };
          throw: false;
        } = {
          throw: false,
        };
        if (cachedToken && decodeJwtExp(cachedToken) === null) {
          fetchOptions.credentials = 'omit';
          fetchOptions.headers = {
            Authorization: `Bearer ${cachedToken}`,
          };
        }

        // biome-ignore lint/suspicious/noExplicitAny: convex plugin type
        pendingTokenRef.current = (authClient as any).convex
          .token({ fetchOptions })
          .then((result: { data?: { token?: string | null } | null }) => {
            const jwt = result.data?.token || null;

            if (jwt) {
              const exp = decodeJwtExp(jwt);
              authStore.set('token', jwt);
              authStore.set('expiresAt', exp);
              authStore.set('sessionSyncGraceUntil', null);
              return jwt;
            }

            const cachedJwt = getCachedJwt();
            if (cachedJwt) {
              authStore.set('expiresAt', decodeJwtExp(cachedJwt));
              authStore.set('sessionSyncGraceUntil', null);
              return cachedJwt;
            }

            authStore.set('token', null);
            authStore.set('expiresAt', null);
            authStore.set('sessionSyncGraceUntil', null);
            return null;
          })
          .catch((error: unknown) => {
            const cachedJwt = getCachedJwt();
            if (cachedJwt) {
              authStore.set('expiresAt', decodeJwtExp(cachedJwt));
              authStore.set('sessionSyncGraceUntil', null);
              return cachedJwt;
            }

            authStore.set('token', null);
            authStore.set('expiresAt', null);
            authStore.set('sessionSyncGraceUntil', null);
            console.error('[fetchAccessToken] error', error);
            return null;
          })
          .finally(() => {
            pendingTokenRef.current = null;
          });

        return pendingTokenRef.current;
      };

      const fetchFreshTokenForced = async () => {
        // For forced refresh, if we only have an in-flight request and it
        // resolves null, retry once immediately instead of returning null.
        const cachedJwt = getCachedJwt();
        if (pendingTokenRef.current) {
          const token = await pendingTokenRef.current;
          if (token && (!cachedJwt || token !== cachedJwt)) {
            return token;
          }
        }

        return fetchFreshToken();
      };

      const currentSession = sessionRef.current;
      const currentIsPending = isPendingRef.current;
      const hasSession = hasActiveSessionData(currentSession);
      const hasSessionSyncGrace = isSessionSyncGraceActive(
        authStore.get('sessionSyncGraceUntil')
      );

      // If no session:
      // - If still pending (hydration), return cached SSR token for non-forced reads
      // - If the cached token is an opaque Better Auth session token, exchange it
      //   before handing auth to Convex
      // - If still pending + forced refresh, fetch a fresh token for Convex scheduling
      // - If not pending (confirmed no session), clear cache
      if (!hasSession) {
        if (currentIsPending || hasSessionSyncGrace) {
          const cachedJwt = getCachedJwt();

          if (!forceRefreshToken) {
            if (cachedJwt) {
              return cachedJwt;
            }

            return fetchFreshToken();
          }

          const freshToken = await fetchFreshTokenForced();

          // During hydration, keep a cached JWT on transient forced-refresh failure.
          // Convex asked for a fresh token, but dropping auth to null here can
          // briefly flip to unauthenticated before Better Auth session settles.
          if (!freshToken && cachedJwt) {
            authStore.set('token', cachedJwt);
            authStore.set('expiresAt', decodeJwtExp(cachedJwt));
            return cachedJwt;
          }

          return freshToken;
        }

        authStore.set('token', null);
        authStore.set('expiresAt', null);
        authStore.set('sessionSyncGraceUntil', null);
        return null;
      }

      // Check cached JWT from store
      const cachedToken = authStore.get('token');
      const expiresAt = authStore.get('expiresAt');
      const timeRemaining = expiresAt ? expiresAt - Date.now() : 0;

      // Return cached if valid and not forced (60s leeway)
      if (
        !forceRefreshToken &&
        cachedToken &&
        expiresAt &&
        timeRemaining >= 60_000
      ) {
        return cachedToken;
      }

      if (!forceRefreshToken && pendingTokenRef.current) {
        return pendingTokenRef.current;
      }

      if (forceRefreshToken) {
        return fetchFreshTokenForced();
      }

      return fetchFreshToken();
    },
    // Stable deps - authStore/authClient rarely change
    // session/isPending accessed via refs to prevent callback recreation
    [authStore, authClient, getCachedJwt]
  );

  // Create useAuth hook for ConvexProviderWithAuth
  // The hook itself is stable - it reads current values from refs
  // This prevents Convex SDK from calling setAuth() on every session refetch
  const useAuth = useCallback(
    function useConvexAuthHook() {
      const token = authStore.get('token');
      const hasSession = hasActiveSessionData(sessionRef.current);
      const sessionMissing = !hasSession && !isPendingRef.current;
      return {
        isLoading: isPendingRef.current && !token,
        // If Better Auth confirms no session, stale JWT should not keep auth=true.
        isAuthenticated: sessionMissing ? false : hasSession || token !== null,
        fetchAccessToken,
      };
    },
    [fetchAccessToken, authStore]
  );

  return (
    <FetchAccessTokenContext.Provider value={fetchAccessToken}>
      <ConvexProviderWithAuth
        client={client as IConvexReactClient}
        useAuth={useAuth}
      >
        <AuthStateSync>{children}</AuthStateSync>
      </ConvexProviderWithAuth>
    </FetchAccessTokenContext.Provider>
  );
}

/**
 * Syncs auth state from useConvexAuth() to the auth store.
 * MUST be inside ConvexProviderWithAuth to access useConvexAuth().
 *
 * Defensive isLoading computation handles SSR hydration race:
 * 1. SSR sets token from cookie
 * 2. Client hydrates
 * 3. Better Auth's useSession() briefly returns null before loading cookie
 * 4. Convex sets isConvexAuthenticated = false (no auth to wait for)
 * 5. Without defensive check, we'd sync { isLoading: false, isAuthenticated: false }
 * 6. Queries would throw UNAUTHORIZED before token is validated
 */
function AuthStateSync({ children }: { children: ReactNode }) {
  const { isLoading: convexIsLoading, isAuthenticated } = useConvexAuth();
  const authStore = useAuthStore();
  const token = useAuthValue('token');

  useEffect(() => {
    // DEFENSIVE: If we have a token but Convex says not authenticated,
    // stay in loading state to avoid UNAUTHORIZED errors during hydration
    const hasTokenButNotAuth = !!token && !isAuthenticated;
    const isLoading = convexIsLoading || hasTokenButNotAuth;

    authStore.set('isLoading', isLoading);
    authStore.set('isAuthenticated', isAuthenticated);
  }, [convexIsLoading, isAuthenticated, token, authStore]);

  return children;
}

/**
 * Handles cross-domain one-time token (OTT) verification.
 */
function useOTTHandler(authClient: ConvexAuthProviderClient) {
  useEffect(() => {
    (async () => {
      if (typeof window === 'undefined' || !window.location?.href) {
        return;
      }
      const url = new URL(window.location.href);
      const token = url.searchParams.get('ott');

      if (token) {
        // biome-ignore lint/suspicious/noExplicitAny: cross-domain plugin type
        const authClientWithCrossDomain = authClient as any;
        url.searchParams.delete('ott');
        window.history.replaceState({}, '', url);
        const result =
          await authClientWithCrossDomain.crossDomain.oneTimeToken.verify({
            token,
          });
        const session = result.data?.session;

        if (session && typeof authClient.getSession === 'function') {
          const getSession = authClient.getSession as AuthGetSession;
          await getSession({
            fetchOptions: {
              credentials: 'omit',
              headers: {
                Authorization: `Bearer ${session.token}`,
              },
            },
          });
          authClientWithCrossDomain.updateSession();
        }
      }
    })();
  }, [authClient]);
}
